mtac/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.contrib import admin
from scheduler.views import *

urlpatterns = patterns('',
    # Examples:
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^scheduler/', include('scheduler.urls')),
    url(r'^schedule/', include('schedule.urls')),
    # override api call to the view in scheduler.api_occurrences
    url(r'^admin/', include(admin.site.urls)),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


# if settings.DEBUG:
#     urlpatterns += patterns('',
#         (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
#         (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
#     )

scheduler/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from views import (
	ReportFilterView,
	FacultyLoadFilterView,
	report
)
urlpatterns = patterns('',
    url(r'^fullcalendar/', TemplateView.as_view(template_name="fullcalendar.html"), name='fullcalendar'),
    url(r'^api/occurrences', 'scheduler.views.api_occurrences', name='api_occurences'),
    url(r'^report$', report, name='report'),
    url(r'^faculty-load/report/$', TemplateView.as_view(template_name='faculty_report.html'), name='faculty-load-report'),
	url(r'^report/filter/$', ReportFilterView.as_view(), name='report-filter'),
	url(r'^faculty-load/filter/$', FacultyLoadFilterView.as_view(), name='faculty-load-filter'),
)

scheduler/models.py
import time

from schedule import models as s
from django.utils.translation import ugettext_lazy as _
from django.db import models
from profiler import models as pm
# Create your models here.

class BaseModel(models.Model):

    creation_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Time(BaseModel):
    """
    This represents a time table
    we create fixed time slots for a class 

    Time start=8:00am end=9:00am
    """
    start = models.TimeField()
    end = models.TimeField()

    class Meta:
        verbose_name = _('Time slot')
        verbose_name_plural = _('Time slots')

    def __unicode__(self):
        start = self.start.strftime("%H:%M %p")
        end = self.end.strftime("%H:%M %p")
        return " - ".join([start, end])

class ClassManager(models.Manager):

    def filter_class(self, *args, **kwargs):
        return self.filter(*args, **kwargs).select_related('course', 'module', 'event', 'instructor')

class Class(BaseModel):
    """
    This refers to a Class instance where  a course is given a time slot
    and date. There is also an instructor override field for cases where 
    an instructor can't teach on a specific time and date.
    """
    batch_number = models.CharField(max_length=50)
    course = models.ForeignKey(pm.Course)
    module = models.ForeignKey(pm.Module, blank=True, null=True,
        related_name='classes')
    instructor = models.ForeignKey(pm.Employee, blank=True, related_name='classes')
    event = models.OneToOneField(s.Event, related_name='get_class')
    # event = models.ManyToManyField(s.Event, related_name='classes')
    hours = models.IntegerField(default=8, 
                help_text=_("This represents the number of hours the \
                            Class in taught in a day."))
    time_slot = models.ForeignKey(Time)

    objects = ClassManager()

    class Meta:
        verbose_name = _('Class')
        verbose_name_plural = _('Classes')


    def __unicode__(self):
        # return self.batch_number
        return " - ".join([self.batch_number, unicode(self.course), self.instructor.get_name()])
        # return " | ".join([self.batch_number, unicode(self.course), unicode(self.instructor)])

    def faculty_load_format(self):
        return "{s.course} ({s.batch_number})".format(s=self)

scheduler/forms.py
from django import forms
from profiler import models as pm
from django.utils.translation import ugettext_lazy as _

class ReportFilterForm(forms.Form):
    start_date = forms.DateTimeField(required=False, widget=forms.HiddenInput())
    end_date = forms.DateTimeField(required=False, widget=forms.HiddenInput())
    batch_number = forms.CharField()
    course = forms.ModelChoiceField(queryset=pm.Course.objects.all())
    
    def __init__(self, *args, **kwargs):
    	super(ReportFilterForm, self).__init__(*args, **kwargs)
    	for key, field in self.fields.iteritems():
	    	field.widget.attrs = {'class': 'form-control'}

class FacultyLoadFilterForm(forms.Form):
    start_date = forms.DateTimeField(required=False, widget=forms.HiddenInput())
    end_date = forms.DateTimeField(required=False, widget=forms.HiddenInput())
    instructor = forms.ModelChoiceField(queryset=pm.Employee.objects.all())
    
    def __init__(self, *args, **kwargs):
        super(FacultyLoadFilterForm, self).__init__(*args, **kwargs)
        for key, field in self.fields.iteritems():
            field.widget.attrs = {'class': 'form-control'}

scheduler/views.py
import json
import pytz
import datetime

from django.utils.timezone import utc
from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.http import HttpResponse, Http404
from django.views.generic import View
from django.shortcuts import render

from schedule.models import Calendar, Occurrence, Event
from .forms import ReportFilterForm, FacultyLoadFilterForm
from .templatetags.template_tag import hours
from .models import Class
from .utils import groupby_date


# Create your views here.
class ReportFilterView(View):
    form_class = ReportFilterForm
    template_name = 'report_filter.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            # <process form cleaned data>
            start = form.cleaned_data['start_date']
            end = form.cleaned_data['end_date']
            events = []
            for _class in Class.objects.filter(batch_number=form.cleaned_data['batch_number'],
                                               course_id=form.cleaned_data['course'],
                                               event__start__gte=start,
                                               event__end__lte=end).order_by('event__start')\
                                               .select_related('event'):
                events.extend(_class.event.get_occurrences(start, end))
            events = groupby_date(events)
            start = start.strftime('%m/%d/%Y')
            end = end.strftime('%m/%d/%Y')
            return render(request, self.template_name, {
                     'form': form, 
                     'events': events,
                     'start_date': start,
                     'end_date': end,
                     'batch_number': form.cleaned_data['batch_number'],
                     'course': form.cleaned_data['course'].id
            })

        return render(request, self.template_name, {'form': form})

class FacultyLoadFilterView(View):
    form_class = FacultyLoadFilterForm
    template_name = 'faculty_load_filter.html'
    report_template_name = 'faculty_report.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            # <process form cleaned data>
            start = form.cleaned_data['start_date']
            end = form.cleaned_data['end_date']
            events_list = []
            events = Event.objects.filter(
                        Q(end_recurring_period__gte=start) | Q(end_recurring_period__lte=end),
                        Q(start__gte=start) | Q(end__lte=end),
                        get_class__instructor_id=form.cleaned_data['instructor'],
                        ).order_by('start').select_related('get_class')
            for event in events:
                events_list.extend(event.get_occurrences(start, end))
            events_list.sort(key=lambda e: e.start)
            # get the total number of hours excluding lunch time in 
            total_hours = sum((hours(e.start, e.end) for e in events_list))
            start = start.strftime('%m/%d/%Y')
            end = end.strftime('%m/%d/%Y')
            ctx = {
             'form': form, 
             'occurrences': events_list,
             'start_date': start,
             'end_date': end,
             'total_hours': total_hours,
             'instructor': form.cleaned_data['instructor']
            }
            if request.POST.get('report'):
                return render(request, self.report_template_name, ctx)
            return render(request, self.template_name, ctx)

        return render(request, self.template_name, {'form': form})

def report(request):
    form = ReportFilterForm(request.POST)
    if form.is_valid():
        # <process form cleaned data>
        start = form.cleaned_data['start_date']
        end = form.cleaned_data['end_date']
        events = []
        for _class in Class.objects.filter(batch_number=form.cleaned_data['batch_number'],
                                           course_id=form.cleaned_data['course'],
                                           event__start__gte=start,
                                           event__end__lte=end).order_by('event__start')\
                                           .select_related('event'):
            events.extend(_class.event.get_occurrences(start, end))
        events = groupby_date(events)
        start = start.strftime('%m/%d/%Y')
        end = end.strftime('%m/%d/%Y')
        return render(request, 'basic_training.html', {
                 'events': events,
                 'start_date': start,
                 'end_date': end,
                 'batch_number': form.cleaned_data['batch_number'],
                 'course': form.cleaned_data['course'].id
        })
    else:
        raise Http404



def api_occurrences(request):
    '''
    this is the same as with schedule.views.api_occurrences
    overrided urls to point to this view
    the only difference on this is the title
    '''
    utc=pytz.UTC
    from django.db import connection
    print 'Start ' + str(len(connection.queries))
    # version 2 of full calendar
    if '-' in request.GET.get('start'):
        convert = lambda d: datetime.datetime.strptime(d, '%Y-%m-%d')
    else:
        convert = lambda d: datetime.datetime.utcfromtimestamp(float(d))
    start = utc.localize(convert(request.GET.get('start')))
    end = utc.localize(convert(request.GET.get('end')))
    calendar = get_object_or_404(Calendar, slug=request.GET.get('calendar_slug'))
    response_data =[]
    for event in calendar.events.filter(start__gte=start, end__lte=end).select_related('get_class', 'get_class__course', 'get_class__module').prefetch_related('get_class__instructor'):
        occurrences = event.get_occurrences(start, end)
        for occurrence in occurrences:
            # http://fullcalendar.io/docs/event_data/Event_Object/
            response_data.append({
                "id": occurrence.id,
                "title": unicode(occurrence.event.get_class),
                "start": occurrence.start.isoformat(),
                "end": occurrence.end.isoformat(),
                "url": reverse('admin:schedule_event_change', args=[occurrence.event.id])

            })
    print 'End ' + str(len(connection.queries))
    return HttpResponse(json.dumps(response_data), content_type="application/json")

scheduler/templates/base_report.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/report.css">
	</head>

	<body>
		<div id="wrapper">
			<div id="header">
				<div id="dcsp_logo">
					<img src="{{ STATIC_URL }}/img/dcsp_logo.jpg" width="100px"  height="80px">
				</div>
				<div id="title">
					DMMA COLLEGE OF SOUTHERN PHILIPPINES <br/>
					(Formerly Davao Merchant Marine Academy) <br/>
					Tigatto Road, Buhangin, Davao City, 8000 <br/>
					Philippines
				</div>
				<div id="dnv_logo">
					<img src="{{ STATIC_URL }}/img/dnv_logo.jpg" width="100px"  height="80px">
				</div>
				<div style="clear: both"></div>

				{% block header %}
				{% endblock header %}
			</div>
			{% block body %}
			{% endblock body %}

			<div id="footer">
				<!-- this is most likely to be signature -->
				<div id="prepared-by">
					<p>
					Prepared by:<br/><br/>
					<b>JACINTA P. SARINO</b><br/>
					<i>Scheduling Officer</i>
					</p>
				</div>

				<div id="noted-by">
					<p>
					Noted by: <br/><br/>
					<div id='noted-by-signature'>
						<b>VICENTE C. VIRTUDAZO</b><br/>
		                <i>Training Director</i>
	                </div>
				</div>
			</div>
			{% block footer %}
			{% endblock footer %}
		</div>
	</body>
</html>

scheduler/templates/basic_training.html
{% extends "training_load_report.html" %}
{% load template_tag %}

{% block body %}
<div id='course'>BASIC TRAINING</div>
<div id='batch'>BATCH NO. <span>{{ batch_number }}</span></div>

<table id='basic-training' border='1'>
<thead>
		<th>DAY/DATE</th>
		<th>TIME</th>
		<th>MODULE</th>
        <th>INSTRUCTOR</th>
</thead>
<tbody>
	{% for date, occurrences in events  %}
		<tr>
			<td>Day-{{ forloop.counter }} ({{ date|date:"D" }}.)<br/><br/>
				{{ date }}
			</td>
			<td>{% for time_slot in occurrences|make_list:'start_end_time'|remove_duplicate %}{{ time_slot }}<br/>
				{% endfor %}</td>
			<td>{% for module in occurrences|make_list:'event.get_class.module'|remove_duplicate %}{{ module }}<br/>{% endfor %}
			</td>
			<td>{% for instructor in occurrences|make_list:'event.get_class.instructor'|remove_duplicate %}{{ instructor }}<br/>{% endfor %}</td>
		</tr>
	{% endfor %}
</tbody>
</table>
{% endblock body %}

scheduler/templates/faculty_load_filter.html
{% extends "report_filter.html" %}
{% load template_tag %}

{% block extra_head %}
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/daterangepicker-bs3.css">
{% endblock extra_head %}
{% block body %}
	<!-- REPORT FILTER FORM -->
	<h1>Report Filter</h1>
	  <form action="{% url 'faculty-load-filter' %}" method="post">
	  <div class='form-group'>
			<div id="reportrange" class="pull-left" style="background: #fff; cursor: pointer; padding: 5px 10px; border-right: 1px solid #ccc;border-top: 1px solid #ccc;border-bottom: 1px solid #ccc;border-left: 1px solid #ccc;">
			  <i class="glyphicon glyphicon-calendar icon-calendar"></i>
			  <span>
			  	{% if start_date and end_date %}
				    {{ start_date }} - {{ end_date }}
				    {% else %}
				    Date Range
			    {% endif %}
			  </span>
			</div>
			<div style='clear: both'></div>
		</div>

	    {% csrf_token %}
	    {% for field in form %}
	    	{% if field.is_hidden %}
	    		{{ field }}
	    	{% else %}
			<div class="form-group">
			    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
			    {{ field.errors }}
			    {{ field }}
			  </div>
	    	{% endif %}
		{% endfor %}    
	    <input class="btn btn-default" type="submit" value="Submit" />
	  </form>
	<!-- END REPORT FILTER FORM -->

	{% if occurrences %}
	<!-- DISPLAY OCCURRENCE OF EVENTS/CLASS -->
	<table class="table table-bordered table-hover" id='basic-training' border='1' style='margin-top: 20px;'>
	<thead>
			<th>Name of Instructors &amp; <br/>Signature</th>
			<th>Course &amp; Batch No.</th>
			<th>Date</th>
			<th>Time</th>
			<th>No. of hours</th>
	</thead>
	<tbody>
	<tr>
		<td>{{ instructor }}</td>
		<td style='text-align: left'>
			{% for occurrence in occurrences %}
				{{ occurrence.event.get_class.faculty_load_format }}<br/>
			{% endfor %}
		</td>
		<td>
			{% for occurrence in occurrences %}
				{{ occurrence.start.date }}<br/>
			{% endfor %}
		</td>
		<td>
			{% for occurrence in occurrences %}
				{{ occurrence.start_end_time }}<br/>
			{% endfor %}
		</td>
		<td>
			{% for occurrence in occurrences %}
				{{ occurrence.start|hours:occurrence.end }}<br/>
			{% endfor %}
		</td>
	<tr>
	<tr>
		<td colspan='4' style='text-align: right; padding-top: 50px;'><b>Total</b></td>
		<td style="padding-top: 50px;"><b>{{ total_hours }}</b></td>
	</tr>
	</tbody>
	</table>
	{% endif %}
	
	{% if occurrences %}
	<div class='pull-right'>
	<form action="{% url 'faculty-load-filter' %}" method='POST'>
		{% csrf_token %}
		<input type='hidden' value='{{ start_date }}' name='start_date' />
		<input type='hidden' value='{{ end_date }}' name='end_date' />
		<input type="hidden" value="{{ instructor.id }}" name="instructor" />
		<input type='hidden' value='true' name='report' />
		<button class="btn">Print</button>
		<button class="btn">Export to xlsx</button>
	</form>
	</div>
	{% endif %}
	<!-- END DISPLAY OCCURRENCE OF EVENTS/CLASS -->

{% endblock body %}


{% block extra_body %}

	<script type="text/javascript" src="//cdn.jsdelivr.net/momentjs/2.9.0/moment.min.js"></script>
	<script type="text/javascript" src="{{ STATIC_URL }}js/daterangepicker.js"></script>
	<script type="text/javascript" src="{{ STATIC_URL }}js/custom-daterangepicker.js"></script>
	<script type="text/javascript">
		$(function (){
			$('input#id_start_end_date').daterangepicker();
			// $('input#id_end_date').datepicker(options);
			// body...
		})
	</script>
{% endblock extra_body %}

scheduler/templates/faculty_load_report.html
{% extends "base_report.html" %}

{% block header %}
	<div id='sub-title'>
		<strong>FACULTY LOAD REPORT<br/>
		(DCSP-T&amp;AC-099, Rev. 1, Jan. 21, 2014)</strong>
	</div>
{% endblock header %}

scheduler/templates/faculty_report.html
{% extends 'faculty_load_report.html' %}
{% load template_tag %}


{% block body %}
<div>Date Prepared: May 2, 2015</div>	{% if occurrences %}
<!-- DISPLAY OCCURRENCE OF EVENTS/CLASS -->
<table class="table table-bordered table-hover" id='basic-training' border='1' style='margin-top: 20px;'>
<thead>
		<th>Name of Instructors &amp; <br/>Signature</th>
		<th>Course &amp; Batch No.</th>
		<th>Date</th>
		<th>Time</th>
		<th>No. of hours</th>
</thead>
<tbody>
<tr>
	<td>{{ instructor }}</td>
	<td style='text-align: left'>
		{% for occurrence in occurrences %}
			{{ occurrence.event.get_class.faculty_load_format }}<br/>
		{% endfor %}
	</td>
	<td>
		{% for occurrence in occurrences %}
			{{ occurrence.start.date }}<br/>
		{% endfor %}
	</td>
	<td>
		{% for occurrence in occurrences %}
			{{ occurrence.start_end_time }}<br/>
		{% endfor %}
	</td>
	<td>
		{% for occurrence in occurrences %}
			{{ occurrence.start|hours:occurrence.end }}<br/>
		{% endfor %}
	</td>
<tr>
<tr>
	<td colspan='4' style='text-align: right; padding-top: 50px;'><b>Total</b></td>
	<td style="padding-top: 50px;"><b>{{ total_hours }}</b></td>
</tr>
</tbody>
</table>
{% endif %}

<div>Note: Please secure IG and TCROA before the training schedule.</div>

{% endblock body %}

scheduler/templates/fullcalendar.html
{% extends "base.html" %}


{% load i18n staticfiles %}

{% block head_title %}{% trans "Fullcalendar" %}{% endblock %}

{% block tab_id %}id="home_tab"{% endblock %}

{% block extra_head %}
<link rel='stylesheet' type='text/css' href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/1.6.4/fullcalendar.css" />
{% endblock %}

{% block body %}
<div id="calendar"></div>
<script type='text/javascript'>
$(document).ready(function() {

    // page is now ready, initialize the calendar...
    $('#calendar').fullCalendar({
        // put your options and callbacks here
      events: '/scheduler/api/occurrences?calendar_slug=mtac',
      header : {
	      right: 'today prev,next basicDay basicWeek month'
      },
      businessHours: {
	    start: '08:00', // a start time (10am in this example)
	    end: '17:00', // an end time (6pm in this example)

	    dow: [ 1, 2, 3, 4, 5 ]
	    // days of week. an array of zero-based day of week integers (0=Sunday)
	    // (Monday-Thursday in this example)
	  }
    })

});
</script>

<script type='text/javascript' src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/1.6.4/fullcalendar.min.js"></script>

{% endblock %}

scheduler/templates/report_filter.html
{% extends "base.html" %}
{% load template_tag %}

{% block extra_head %}
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/daterangepicker-bs3.css">
{% endblock extra_head %}
{% block body %}
	<!-- REPORT FILTER FORM -->
	<h1>Report Filter</h1>
	  <form action="{% url 'report-filter' %}" method="post">
	  <div class='form-group'>
			<div id="reportrange" class="pull-left" style="background: #fff; cursor: pointer; padding: 5px 10px; border-right: 1px solid #ccc;border-top: 1px solid #ccc;border-bottom: 1px solid #ccc;border-left: 1px solid #ccc;">
			  <i class="glyphicon glyphicon-calendar icon-calendar"></i>
			  <span>
			  	{% if start_date and end_date %}
				    {{ start_date }} - {{ end_date }}
				    {% else %}
				    Date Range
			    {% endif %}
			  </span>
			</div>
			<div style='clear: both'></div>
		</div>

	    {% csrf_token %}
	    {% for field in form %}
	    	{% if field.is_hidden %}
	    		{{ field }}
	    	{% else %}
			<div class="form-group">
			    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
			    {{ field }}
			  </div>
	    	{% endif %}
		{% endfor %}    
	    <input class="btn btn-default" type="submit" value="Submit" />
	  </form>
	<!-- END REPORT FILTER FORM -->

	<!-- DISPLAY OCCURRENCE OF EVENTS/CLASS -->
	<table class="table table-bordered table-hover" id='basic-training' border='1' style='margin-top: 20px;'>
	<thead>
			<th>DAY/DATE</th>
			<th>TIME</th>
			<th>MODULE</th>
	        <th>INSTRUCTOR</th>
	</thead>
	<tbody>
  	{% for date, occurrences in events  %}
		<tr>
			<td>Day-{{ forloop.counter }} ({{ date|date:"D" }}.)<br/><br/>
				{{ date }}
			</td>
			<td>{% for time_slot in occurrences|make_list:'start_end_time'|remove_duplicate %}{{ time_slot }}<br/>
				{% endfor %}</td>
			<td>{% for module in occurrences|make_list:'event.get_class.module'|remove_duplicate %}{{ module }}<br/>{% endfor %}
			</td>
			<td>{% for instructor in occurrences|make_list:'event.get_class.instructor'|remove_duplicate %}{{ instructor }}<br/>{% endfor %}</td>
		</tr>
	{% endfor %}
	</tbody>
	</table>
	{% if events %}
	<div class='pull-right'>
	<form action="{% url 'report' %}" method='POST'>
		{% csrf_token %}
		<input type='hidden' value='{{ batch_number }}' name='batch_number' />
		<input type='hidden' value='{{ course }}' name='course'/>
		<input type='hidden' value='{{ start_date }}' name='start_date' />
		<input type='hidden' value='{{ end_date }}' name='end_date' />
		<button class="btn">Print</button>
		<button class="btn">Export to xlsx</button>
	</form>
	</div>
	{% endif %}
	<!-- END DISPLAY OCCURRENCE OF EVENTS/CLASS -->

{% endblock body %}


{% block extra_body %}

	<script type="text/javascript" src="//cdn.jsdelivr.net/momentjs/2.9.0/moment.min.js"></script>
	<script type="text/javascript" src="{{ STATIC_URL }}js/daterangepicker.js"></script>
	<script type="text/javascript" src="{{ STATIC_URL }}js/custom-daterangepicker.js"></script>
	<script type="text/javascript">
		$(function (){
			$('input#id_start_end_date').daterangepicker();
			// $('input#id_end_date').datepicker(options);
			// body...
		})
	</script>
{% endblock extra_body %}

scheduler/templates/training_load_report.html
{% extends "base_report.html" %}

{% block header %}
	<div id='sub-title'>
		<strong>TRAINING DEPARTMENT FACULTY LOAD REPORT<br/>
		(DCSP-TD-043, Rev 1, Jan. 21, 2014)</strong>
	</div>
{% endblock header %}